### ISSUE TITLE
Has a reload animation issue similar to the CGM unofficial port

### ISSUE THREAD

**Issue by Aabyiswack** [ribs498/Scorched-Guns-1.20.1#1]
to elaborate more and to reproduce:

the reload animations work fine at first but after the player is killed once the reload animation gets stuck on a loop when trying to reload the gun again

**Comment by ribs498** [comment]
Im trying to replicate it, but i cant seem to, was there any guns in particular causing it? do you have keep inventory on? is this serverside or single player?

**Comment by ribs498** [comment]
OK i was able to replicate it, working on it right now :)

**Comment by Aabyiswack** [comment]
apparently it still does occur even after the 0.05 update, ima attach a video file to how reproduce 

https://github.com/user-attachments/assets/10699a42-ee8d-4451-97a2-33c3664e9da7

on the first log in of the world the issue does not occur, but after setting keepinv to true and killing the player and initiating a reload it gets stuck in the animation,

before i was testing in a heavily modded environment, but this is fairly vanilla with just optimization mods which are crucial to the modpack which i am going to include scguns in
