### ISSUE TITLE
Geothermal Vent produces niter without needing a magma block or waterlogging

### ISSUE THREAD

**Issue by MCRusher** [ribs498/Scorched-Guns-1.20.1#11]
Even when a vent is not marked as active it will still produce niter if waterlogged

Actually it just needs some water in the immediate vicinity, waterlogging it doesn't seem to matter.

Just waterlogging the block itself doesn't allow it to produce niter so waterlogging actually seems completely irrelevant to its function currently.

I tested it with the latest modrinth, curseforge, and compiled the current commit version from github, seems present in all 3.

![2024-08-04_00 31 54](https://github.com/user-attachments/assets/4e23ea1c-cde1-4b23-8a2e-c956072a0a62)

![2024-08-04_01 32 00](https://github.com/user-attachments/assets/3331f52b-eba6-4432-b25f-b2a761e96f76)

**Comment by ribs498** [comment]
Will fix, thanks!

**Comment by MCRusher** [comment]
Looks like it's fixed now, thank you.
