### ISSUE TITLE
Has a reload animation issue similar to the CGM unofficial port (still occurs)

### ISSUE THREAD

**Issue by Aabyiswack** [ribs498/Scorched-Guns-1.20.1#2]
apparently it still does occur even after the 0.0.5 and 0.0.6 update, ima attach a video file on how to reproduce

https://github.com/user-attachments/assets/02a343fc-130d-41e6-865d-690aefb7bfb1

on the first log in of the world the issue does not occur, but after setting keepinv to true and killing the player and initiating a reload it gets stuck in the animation.

before i was testing in a heavily modded environment, but this is fairly vanilla with just optimization mods which are crucial to the modpack which i am going to include scguns in.

**Comment by ribs498** [comment]
Are you using the Framework 0.7.6? Ive pinpointed to that being the issue, you will have to downgrade, Framework 0.6.27 seems to work.

**Comment by Aabyiswack** [comment]
yup that was the case it seems, its fixed now ty
